package net.melissadata.address;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-01-18T14:29:11.710+01:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:mdGlobalAddress", name = "AddressCheckSoap")
@XmlSeeAlso({net.melissadata.address.types.ObjectFactory.class})
public interface AddressCheckSoap {

    @WebMethod(action = "urn:mdGlobalAddress/AddressCheckSoap/doGlobalAddress")
    @Action(input = "urn:mdGlobalAddress/AddressCheckSoap/doGlobalAddress", output = "urn:mdGlobalAddress/AddressCheckSoap/doGlobalAddressResponse")
    @RequestWrapper(localName = "doGlobalAddress", targetNamespace = "urn:mdGlobalAddress", className = "net.melissadata.address.types.DoGlobalAddress")
    @ResponseWrapper(localName = "doGlobalAddressResponse", targetNamespace = "urn:mdGlobalAddress", className = "net.melissadata.address.types.DoGlobalAddressResponse")
    @WebResult(name = "doGlobalAddressResult", targetNamespace = "urn:mdGlobalAddress")
    public net.melissadata.address.types.Response doGlobalAddress(
        @WebParam(name = "Request", targetNamespace = "urn:mdGlobalAddress")
        net.melissadata.address.types.Request request
    );
}
