package net.melissadata.address;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-01-18T14:29:11.725+01:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "AddressCheckSoap",
                  wsdlLocation = "file:/C:/Users/v.kolesnikov/Documents/project%20java/ecom-spring/ecom-rpe-melissa/src/main/resources/wsdl/GlobalAddress.wsdl",
                  targetNamespace = "urn:mdGlobalAddress")
public class AddressCheckSoap_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:mdGlobalAddress", "AddressCheckSoap");
    public final static QName SoapEndpointGlobalAddressCheck = new QName("urn:mdGlobalAddress", "soapEndpointGlobalAddressCheck");
    public final static QName SoapSSLEndpointGlobalAddressCheck = new QName("urn:mdGlobalAddress", "soapSSLEndpointGlobalAddressCheck");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/v.kolesnikov/Documents/project%20java/ecom-spring/ecom-rpe-melissa/src/main/resources/wsdl/GlobalAddress.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AddressCheckSoap_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/v.kolesnikov/Documents/project%20java/ecom-spring/ecom-rpe-melissa/src/main/resources/wsdl/GlobalAddress.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AddressCheckSoap_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AddressCheckSoap_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddressCheckSoap_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AddressCheckSoap_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AddressCheckSoap_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AddressCheckSoap_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AddressCheckSoap
     */
    @WebEndpoint(name = "soapEndpointGlobalAddressCheck")
    public AddressCheckSoap getSoapEndpointGlobalAddressCheck() {
        return super.getPort(SoapEndpointGlobalAddressCheck, AddressCheckSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressCheckSoap
     */
    @WebEndpoint(name = "soapEndpointGlobalAddressCheck")
    public AddressCheckSoap getSoapEndpointGlobalAddressCheck(WebServiceFeature... features) {
        return super.getPort(SoapEndpointGlobalAddressCheck, AddressCheckSoap.class, features);
    }


    /**
     *
     * @return
     *     returns AddressCheckSoap
     */
    @WebEndpoint(name = "soapSSLEndpointGlobalAddressCheck")
    public AddressCheckSoap getSoapSSLEndpointGlobalAddressCheck() {
        return super.getPort(SoapSSLEndpointGlobalAddressCheck, AddressCheckSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressCheckSoap
     */
    @WebEndpoint(name = "soapSSLEndpointGlobalAddressCheck")
    public AddressCheckSoap getSoapSSLEndpointGlobalAddressCheck(WebServiceFeature... features) {
        return super.getPort(SoapSSLEndpointGlobalAddressCheck, AddressCheckSoap.class, features);
    }

}
